#!/bin/bash

cp -r Template  $1

cd $1

ls |
sed -n 's/\(.*\)\(Template\)\(.*\)/mv "\1\2\3" "\1'$1'\3"/p' |
sh

cd Contracts

ls |
sed -n 's/\(.*\)\(Template\)\(.*\)/mv "\1\2\3" "\1'$1'\3"/p' |
sh

cd ..

LC_ALL=C
find . -type f -name '*.*' -exec sed -i '' s/Template/"$1"/g {} +
